### ISSUE TITLE
2023.05.09 AC와 범용레지스터의 차이가 무엇인지 모르겠습니다.

### ISSUE THREAD

**Issue by moonheee** [SSAFY9-A/Algorithm-A#29]
범용레지스터도 임시값을 저장할 수 있고 AC도 임시값을 저장가능한데 두개의 차이점이 무엇인가요?

**Comment by ccc3017** [comment]
ㅎㅇ

**Comment by bmryu0501** [comment]
CPU 작동 원리가 설명된 유튜브 영상입니다.

특수 목적 레지스터들과 제어장치, 누산기, ALU 들이 어떤 일을 하는지 순차적으로 정리되어 있습니다.

https://youtu.be/Fg00LN30Ezg?t=742

**Comment by moonheee** [comment]
![image](https://github.com/SSAFY9-A/Algorithm-A/assets/30206073/4f27a4a8-be10-4847-b6ba-0ac4b45136f6)

**Comment by ccc3017** [comment]
AC : ALU가 연산(산술, 논리)을 수행할 때, 그 연산 "중간" 값들을 임시적으로 저장해놓는 레지스터이다. 
범용 레지스터 : 컴퓨터의 중앙 처리 장치(CPU) 내에 있는 레지스터 중에서 계산 결과의 임시 저장, 산술 및 논리 연산, 주소 색인 등의 여러 가지 목적으로 사용될 수 있는 레지스터

내 정답 : AC든 범용 레지스터든 어차피 같은 레지스터다. 그냥 우리가 특정 레지스터를 ALU의 중간 연산 결과만을 임시적으로 저장하는 것에 쓰이도록 정하고 그것을 AC라고 부르기로 한 것.

여담 : 현대의 컴퓨터 시스템들은 종종 누산기의 역할을 하는 여러 개의 범용 레지스터를 갖추고 있으므로 이 용어는 더 이상 과거처럼 일상적으로 쓰이지 않는다. 그러나 수많은 특수 목적 프로세서들은 설계의 단순화를 위해 여전히 단순한 누산기를 사용한다.
