### ISSUE TITLE
SSAFY에서 Polling 방식을 사용하는 것들이 나왔는데 잘 기억이 안납니다.

### ISSUE THREAD

**Issue by bmryu0501** [SSAFY9-A/Algorithm-A#37]
SSAFY 수업 중에 Polling 방식을 사용하는 예시들이 있었는데, 어떤 것들이 있었는지 아는대로 알려주세요!

**Comment by jeonghwanin** [comment]
음 버튼을 이용할 때 폴링방식을 했던걸로  알아요
int main(void)
{
	HAL_Init();
	SystemClock_Config();
	MX_GPIO_Init();

	while(1)
	{
		GPIO_PinState pin_state = HAL_GPIO_ReadPin(GPIOA, GPIO_PIN_0);
		if(pin_state == GPIO_PIN_RESET)
		{
			HAL_GPIO_WritePin(GPIOD, GPIO_PIN_12, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOD, GPIO_PIN_13, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOD, GPIO_PIN_14, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOD, GPIO_PIN_15, GPIO_PIN_RESET);
		}
		else
		{
			HAL_GPIO_WritePin(GPIOD, GPIO_PIN_12, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOD, GPIO_PIN_13, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOD, GPIO_PIN_14, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOD, GPIO_PIN_15, GPIO_PIN_SET);
		}
	}
}

폴링방식은 무한루프에서 매 순간마다 확인하는 방식입니다
